/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author liond
 */
public class Creators extends javax.swing.JDialog {

    /**
     * Creates new form Creators
     */
    public Creators(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon imagen= new ImageIcon("src/imagesp/luna.jpg");
        Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(ETIFondo.getWidth(),ETIFondo.getHeight(),Image.SCALE_DEFAULT));
        ETIFondo.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        nom1 = new javax.swing.JLabel();
        nom2 = new javax.swing.JLabel();
        S = new javax.swing.JLabel();
        ETIFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creadores");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Transformers Movie", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Creadores");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 50));

        nom.setBackground(new java.awt.Color(255, 255, 255));
        nom.setFont(new java.awt.Font("Transformers Movie", 0, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setText("-Asencio Ortiz Sergio Noe");
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 190, 30));

        nom1.setFont(new java.awt.Font("Transformers Movie", 0, 14)); // NOI18N
        nom1.setForeground(new java.awt.Color(255, 255, 255));
        nom1.setText("-Castillo Salas Eduardo Enrique");
        getContentPane().add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 260, 30));

        nom2.setFont(new java.awt.Font("Transformers Movie", 0, 14)); // NOI18N
        nom2.setForeground(new java.awt.Color(255, 255, 255));
        nom2.setText("-Martinez Diaz Carlos Daniel");
        getContentPane().add(nom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 240, 30));

        S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesp/Legend.png"))); // NOI18N
        getContentPane().add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, 190));
        getContentPane().add(ETIFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Creators dialog = new Creators(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ETIFondo;
    private javax.swing.JLabel S;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel nom1;
    private javax.swing.JLabel nom2;
    // End of variables declaration//GEN-END:variables
}
