/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sergio
 */

public class ModificarPreguntas extends javax.swing.JFrame {
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    
    /**
     * Creates new form ModificarPreguntas
     */
    public ModificarPreguntas() {
        initComponents();
        ImageIcon imagen= new ImageIcon("src/imagesp/Fon.jpg");
        Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(ETIFondo.getWidth(),ETIFondo.getHeight(),Image.SCALE_DEFAULT));
        ETIFondo.setIcon(icono);
        this.repaint();
    }
     public String AbrirArchivo (File archivo){
       String documento="";
       try{
       entrada=new FileInputStream("preguntas.dat");
       int a;
       while((a=entrada.read())!=-1){
           char car = (char)a;
           documento+=car;
       }
       }
       catch(Exception e){
       }
    return documento;
    }
     public String GuardarArchivo(File archivo,String docuemnto){
     String mensaje=null;
     
     try{
         //salida= new FileOutputStream(archivo);
         byte[] bytxt=docuemnto.getBytes();JOptionPane.showMessageDialog(null,"Prueba");
         salida.write(bytxt);
         mensaje="Archivo Guardado";
     }catch(Exception e){}
     return mensaje;
     }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ATexto = new javax.swing.JTextArea();
        Titulo = new javax.swing.JLabel();
        BTNGuardar = new javax.swing.JButton();
        BTNModificar = new javax.swing.JButton();
        ETIFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificador de Preguntas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ATexto.setColumns(20);
        ATexto.setRows(5);
        getContentPane().add(ATexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 410, 240));

        Titulo.setFont(new java.awt.Font("Transformers Movie", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Preguntas");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, 30));

        BTNGuardar.setBackground(new java.awt.Color(0, 153, 0));
        BTNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BTNGuardar.setText("Guradar");
        BTNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 100, 30));

        BTNModificar.setBackground(new java.awt.Color(0, 153, 0));
        BTNModificar.setForeground(new java.awt.Color(255, 255, 255));
        BTNModificar.setText("Modificar");
        BTNModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 100, 30));
        getContentPane().add(ETIFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarActionPerformed
        // TODO add your handling code here:
        String documento=AbrirArchivo(archivo);
        ATexto.setText(documento);
    }//GEN-LAST:event_BTNModificarActionPerformed

    private void BTNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGuardarActionPerformed
        // TODO add your handling code here:
        String documento=ATexto.getText();
        String mensaje=GuardarArchivo(archivo,documento);
        if(mensaje!=null){
          JOptionPane.showMessageDialog(null,mensaje);
          JOptionPane.showMessageDialog(null,"Hola");
        }else{JOptionPane.showMessageDialog(null,"Archivo no Guardado");
        }
    }//GEN-LAST:event_BTNGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ATexto;
    private javax.swing.JButton BTNGuardar;
    private javax.swing.JButton BTNModificar;
    private javax.swing.JLabel ETIFondo;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
