/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import static Logins.PreguntasRandom.flujo;
import static Logins.PreguntasRandom.getNumeroRegistros;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.LinkedList;

/**
 *
 * @author liond
 */
public class Question extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    LinkedList<Preguntas> objList;
     int puntaje=0;
    Search b;
    int arreglon[]=new int[5];
    public Question() {
        initComponents(); 
        
        objList = new LinkedList<Preguntas>();
        ImageIcon imagen= new ImageIcon("src/imagesp/paisaje.jpg");
       Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(ETIFondo.getWidth(),ETIFondo.getHeight(),Image.SCALE_DEFAULT));
       ETIFondo.setIcon(icono);
        this.repaint();
       
        b=new Search();
    }

     public Question(Object object, boolean b) {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Respuestas = new javax.swing.ButtonGroup();
        btnregreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jR1 = new javax.swing.JRadioButton();
        jR2 = new javax.swing.JRadioButton();
        jR3 = new javax.swing.JRadioButton();
        ETIPregunta = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        jUnidad = new javax.swing.JLabel();
        ETIFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuestionario");
        getContentPane().setLayout(null);

        btnregreso.setBackground(new java.awt.Color(0, 153, 0));
        btnregreso.setForeground(new java.awt.Color(255, 255, 255));
        btnregreso.setText("<-- Regresar");
        btnregreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresoActionPerformed(evt);
            }
        });
        getContentPane().add(btnregreso);
        btnregreso.setBounds(30, 30, 110, 30);

        jLabel2.setFont(new java.awt.Font("Transformers Movie", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contesta y Despega");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 20, 180, 60);

        jPanel1.setLayout(null);

        Respuestas.add(jR1);
        jR1.setText("-----");
        jR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR1ActionPerformed(evt);
            }
        });
        jPanel1.add(jR1);
        jR1.setBounds(20, 20, 180, 23);

        Respuestas.add(jR2);
        jR2.setText("-----");
        jR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jR2MouseClicked(evt);
            }
        });
        jPanel1.add(jR2);
        jR2.setBounds(20, 50, 190, 23);

        Respuestas.add(jR3);
        jR3.setText("-----");
        jR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jR3MouseClicked(evt);
            }
        });
        jPanel1.add(jR3);
        jR3.setBounds(20, 80, 180, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 240, 320, 130);

        ETIPregunta.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ETIPregunta.setForeground(new java.awt.Color(255, 255, 255));
        ETIPregunta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pregunta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12))); // NOI18N
        ETIPregunta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(ETIPregunta);
        ETIPregunta.setBounds(170, 150, 440, 50);

        btnInicio.setBackground(new java.awt.Color(0, 153, 0));
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Iniciar");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(560, 260, 110, 30);

        jUnidad.setForeground(new java.awt.Color(255, 255, 255));
        jUnidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12))); // NOI18N
        getContentPane().add(jUnidad);
        jUnidad.setBounds(170, 90, 430, 50);
        getContentPane().add(ETIFondo);
        ETIFondo.setBounds(0, 0, 850, 510);

        setBounds(0, 0, 811, 521);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresoActionPerformed
          Login prin;
       prin=new Login();
       this.dispose();
       prin.setVisible(true);
       prin.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnregresoActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        try { 
            int t ;
            int i = (int) (Math.random()*PreguntasRandom.getNumeroRegistros()+1);
            String Unidad=Integer.toString(i);
            PreguntasRandom.crearFilePreguntas(new java.io.File ("preguntas.dat"));
           t =PreguntasRandom.buscarRegistro(Unidad);
            ETIPregunta.setText(Preguntas.getPregunta());
            jUnidad.setText(Preguntas.getUnidad());
            jR1.setText(Preguntas.getRes1());
             jR2.setText(Preguntas.getRes2());
              jR3.setText(Preguntas.getRes3());
              
              
              //if(t==-1){JOptionPane.showMessageDialog(this,"nop");}
              PreguntasRandom.cerrar();
             
              
        } catch (IOException ex) {
            
           
        }
       
     
           
    }//GEN-LAST:event_btnInicioActionPerformed

    private void jR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jR2MouseClicked
       
         if(jR2.isSelected()){
         if(jR2.getText().equals(Preguntas.getRes())){
             puntaje=puntaje+1;
         }
         
     }
    }//GEN-LAST:event_jR2MouseClicked

    private void jR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jR3MouseClicked
        
         if(jR3.isSelected()){
         if(jR3.getText().equals(Preguntas.getRes())){
             puntaje=puntaje+1;
         }
         
     }
    }//GEN-LAST:event_jR3MouseClicked

    private void jR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR1ActionPerformed
      
        if(jR1.isSelected()){
         if(jR1.getText().equals(Preguntas.getRes())){
             puntaje=puntaje+1;
             
             try { 
            int t ;
            int i = (int) (Math.random()*PreguntasRandom.getNumeroRegistros()+1);
            String NUM=Integer.toString(i);
            
           t =PreguntasRandom.buscarRegistro(NUM);
            ETIPregunta.setText(Preguntas.getPregunta());
            jUnidad.setText(Preguntas.getUnidad());
            jR1.setText(Preguntas.getRes1());
             jR2.setText(Preguntas.getRes2());
              jR3.setText(Preguntas.getRes3());
              
        } catch (IOException ex) {
            
            Logger.getLogger(Question.class.getName()).log(Level.SEVERE, null, ex);
        }
             
         }else{
              try { 
            int t ;
            int i = (int) (Math.random()*PreguntasRandom.getNumeroRegistros()+1);
            String Unidad=Integer.toString(i);
            
           t =PreguntasRandom.buscarRegistro(Unidad);
            ETIPregunta.setText(Preguntas.getPregunta());
            jUnidad.setText(Preguntas.getUnidad());
            jR1.setText(Preguntas.getRes1());
             jR2.setText(Preguntas.getRes2());
              jR3.setText(Preguntas.getRes3());
              
        } catch (IOException ex) {
            
            Logger.getLogger(Question.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
         
     }
    }//GEN-LAST:event_jR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ETIFondo;
    private javax.swing.JLabel ETIPregunta;
    private javax.swing.ButtonGroup Respuestas;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnregreso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JRadioButton jR1;
    public static javax.swing.JRadioButton jR2;
    public static javax.swing.JRadioButton jR3;
    private javax.swing.JLabel jUnidad;
    // End of variables declaration//GEN-END:variables
}
