/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author liond
 */
public class Login extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    Ventanap prueba;
    Search creador;
    Question cuestionario;
    public Login() {
        initComponents();
        prueba=new Ventanap(null,true);
        creador=new Search(null,true);
        cuestionario=new Question();
        ImageIcon imagen= new ImageIcon("src/imagesp/nave.jpg");
        Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(jLogin.getWidth(),jLogin.getHeight(),Image.SCALE_DEFAULT));
        jLogin.setIcon(icono);
        this.repaint();
        ImageIcon logo =new ImageIcon("src/imagesp/logo.png");
        Icon log = new ImageIcon(logo.getImage().getScaledInstance(ETILogo.getWidth(),ETILogo.getHeight(),Image.SCALE_DEFAULT));
        ETILogo.setIcon(log);
        this.repaint();
         
        // ImageIcon imagen1= new ImageIcon("src/imagesp/adm.png");
       // Icon icono1=new ImageIcon(imagen1.getImage().getScaledInstance(jlop.getWidth(),jlop.getHeight(),Image.SCALE_DEFAULT));
        //jlop.setIcon(icono1);
        //this.repaint();
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        btnEntrada1 = new javax.swing.JButton();
        passContra = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        ETIEslogan = new javax.swing.JLabel();
        ETILogo = new javax.swing.JLabel();
        jRegistro = new javax.swing.JLabel();
        jLogin = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Huragok");
        getContentPane().setLayout(null);

        txtUsuario1.setBackground(java.awt.Color.lightGray);
        txtUsuario1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        txtUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario1);
        txtUsuario1.setBounds(150, 270, 180, 60);

        btnEntrada1.setBackground(new java.awt.Color(0, 153, 0));
        btnEntrada1.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrada1.setText("Ingresar");
        btnEntrada1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrada1MouseClicked(evt);
            }
        });
        btnEntrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrada1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrada1);
        btnEntrada1.setBounds(180, 410, 120, 30);

        passContra.setBackground(java.awt.Color.lightGray);
        passContra.setToolTipText("");
        passContra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        passContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passContraActionPerformed(evt);
            }
        });
        getContentPane().add(passContra);
        passContra.setBounds(150, 340, 180, 60);

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Creadores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 490, 120, 30);

        ETIEslogan.setBackground(new java.awt.Color(255, 255, 255));
        ETIEslogan.setFont(new java.awt.Font("Transformers Movie", 3, 17)); // NOI18N
        ETIEslogan.setForeground(new java.awt.Color(255, 255, 255));
        ETIEslogan.setText("Nosotros Creamos Nuestra Propia Suerte...");
        ETIEslogan.setToolTipText("");
        getContentPane().add(ETIEslogan);
        ETIEslogan.setBounds(60, 30, 420, 100);
        getContentPane().add(ETILogo);
        ETILogo.setBounds(150, 110, 180, 140);

        jRegistro.setFont(new java.awt.Font("Transformers Movie", 3, 14)); // NOI18N
        jRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jRegistro.setText("Registrarse");
        jRegistro.setToolTipText("");
        jRegistro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jRegistroMouseDragged(evt);
            }
        });
        jRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegistroMouseClicked(evt);
            }
        });
        getContentPane().add(jRegistro);
        jRegistro.setBounds(180, 450, 120, 30);
        getContentPane().add(jLogin);
        jLogin.setBounds(0, 0, 510, 530);

        setSize(new java.awt.Dimension(525, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario1ActionPerformed

    private void btnEntrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrada1ActionPerformed
      String nombre = txtUsuario1.getText().trim();
        String contra = passContra.getText();
       if (txtUsuario1.getText().equals("administrador") && contra.equals("123")){
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Bienvenido\n"
                    + "Has ingresado satisfactoriamente al sistema",   "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
                    creador.setLocationRelativeTo(null);
                    creador.setVisible(true);
           

            }else {
                    
          if(nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso el nombre de la persona o la contraseña", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
         } 
         try {
            AccesoAleatorio.crearFileAlumno( new File("personas.dat") );
           
          int i = AccesoAleatorio.buscarRegistro(nombre,contra);
            
            if(i==-1) {
                JOptionPane.showMessageDialog(this, "Ningún registro coincide con los datos de búsqueda.", "Advertencia", JOptionPane.WARNING_MESSAGE);             
                return;
            }
             JOptionPane.showMessageDialog(null, "Bienvenido\n"
                    + "Has ingresado satisfactoriamente al sistema",   "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
            AccesoAleatorio.cerrar();
            dispose();
            cuestionario.setLocationRelativeTo(null);
            cuestionario.setVisible(true);
            cuestionario.setSize(842,549);
            
        } catch(IOException e) {
            JOptionPane.showMessageDialog(this, "Error en la búsqueda de registros.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       }   
    }//GEN-LAST:event_btnEntrada1ActionPerformed

    private void btnEntrada1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrada1MouseClicked
     
    }//GEN-LAST:event_btnEntrada1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     JOptionPane.showMessageDialog(null,"CREADO POR:\n Asencio Ortiz Sergio Noé\n Castillo Salas Eduardo Enrique\n Martinez Diaz Carlos Daniel");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegistroMouseClicked
        dispose();
        prueba.setLocationRelativeTo(null);
        prueba.setVisible(true);
    }//GEN-LAST:event_jRegistroMouseClicked

    private void jRegistroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegistroMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegistroMouseDragged

    private void passContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passContraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               
               Splash s;
               s=new Splash();
               s.setVisible(true);
                new Login().setVisible(true);
                
               
            }

        
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ETIEslogan;
    private javax.swing.JLabel ETILogo;
    private javax.swing.JButton btnEntrada1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLogin;
    private javax.swing.JLabel jRegistro;
    private javax.swing.JPasswordField passContra;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
