/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author liond
 */
public class Question extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Question
     */
    
    Search b;
    public Question() {
        initComponents();
        ImageIcon imagen= new ImageIcon("src/imagesp/paisaje.jpg");
       Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(ETIFondo.getWidth(),ETIFondo.getHeight(),Image.SCALE_DEFAULT));
       ETIFondo.setIcon(icono);
        this.repaint();
       
        b=new Search();
    }

     public Question(Object object, boolean b) {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Respuestas = new javax.swing.ButtonGroup();
        btnregreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        ETIPregunta = new javax.swing.JLabel();
        BTNMostrar = new javax.swing.JButton();
        ETIFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuestionario");
        getContentPane().setLayout(null);

        btnregreso.setBackground(new java.awt.Color(0, 153, 0));
        btnregreso.setForeground(new java.awt.Color(255, 255, 255));
        btnregreso.setText("<-- Regresar");
        btnregreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresoActionPerformed(evt);
            }
        });
        getContentPane().add(btnregreso);
        btnregreso.setBounds(20, 30, 110, 30);

        jLabel2.setFont(new java.awt.Font("Transformers Movie", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contesta y Despega");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 20, 180, 60);

        jPanel1.setLayout(null);

        Respuestas.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(20, 20, 93, 23);

        Respuestas.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(20, 50, 93, 23);

        Respuestas.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(20, 80, 93, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 240, 120, 130);

        ETIPregunta.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ETIPregunta.setForeground(new java.awt.Color(255, 255, 255));
        ETIPregunta.setText("Pregunta");
        ETIPregunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ETIPregunta);
        ETIPregunta.setBounds(200, 120, 440, 50);

        BTNMostrar.setText("Pregunta");
        getContentPane().add(BTNMostrar);
        BTNMostrar.setBounds(420, 260, 110, 30);
        getContentPane().add(ETIFondo);
        ETIFondo.setBounds(0, 0, 830, 510);

        setBounds(0, 0, 811, 521);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresoActionPerformed
          Login prin;
       prin=new Login();
       this.dispose();
       prin.setVisible(true);
       prin.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnregresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNMostrar;
    private javax.swing.JLabel ETIFondo;
    private javax.swing.JLabel ETIPregunta;
    private javax.swing.ButtonGroup Respuestas;
    private javax.swing.JButton btnregreso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
