/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;


import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author liond
 */
public class Search extends javax.swing.JDialog  {

    private static final long serialVersionUID = 1L;
    String p;
    Question recibe;
    PreguntasRandom e;
    public Search(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        e= new PreguntasRandom();
        recibe= new Question();
         ImageIcon imagen= new ImageIcon("src/imagesp/hr.jpg");
        Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(jAdmi.getWidth(),jAdmi.getHeight(),Image.SCALE_DEFAULT));
        jAdmi.setIcon(icono);
        this.repaint();
    
    }

   public Search() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        txtUnidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPregunta = new javax.swing.JTextField();
        txtRes1 = new javax.swing.JTextField();
        txtRes2 = new javax.swing.JTextField();
        txtRes3 = new javax.swing.JTextField();
        btnMo = new javax.swing.JButton();
        jRes = new javax.swing.JTextField();
        jAdmi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador");
        getContentPane().setLayout(null);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("<--  Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(610, 40, 120, 30);

        txtUnidad.setBackground(new java.awt.Color(204, 204, 204));
        txtUnidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUnidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txtUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnidadMouseClicked(evt);
            }
        });
        txtUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadActionPerformed(evt);
            }
        });
        txtUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnidadKeyPressed(evt);
            }
        });
        getContentPane().add(txtUnidad);
        txtUnidad.setBounds(50, 120, 330, 70);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFICACION DE PREGUNTAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 300, 80);

        txtPregunta.setBackground(new java.awt.Color(204, 204, 204));
        txtPregunta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pregunta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        getContentPane().add(txtPregunta);
        txtPregunta.setBounds(40, 40, 150, 50);

        txtRes1.setBackground(new java.awt.Color(204, 204, 204));
        txtRes1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Respuesta 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txtRes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRes1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtRes1);
        txtRes1.setBounds(50, 200, 330, 70);

        txtRes2.setBackground(new java.awt.Color(204, 204, 204));
        txtRes2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Respuesta 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        getContentPane().add(txtRes2);
        txtRes2.setBounds(50, 280, 330, 70);

        txtRes3.setBackground(new java.awt.Color(204, 204, 204));
        txtRes3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Respuesta 3", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txtRes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRes3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtRes3);
        txtRes3.setBounds(50, 360, 330, 70);

        btnMo.setBackground(new java.awt.Color(0, 153, 0));
        btnMo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnMo.setForeground(new java.awt.Color(255, 255, 255));
        btnMo.setText("Agregar");
        btnMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMo);
        btnMo.setBounds(520, 300, 120, 30);

        jRes.setBackground(new java.awt.Color(204, 204, 204));
        jRes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Respuesta 4", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResActionPerformed(evt);
            }
        });
        getContentPane().add(jRes);
        jRes.setBounds(50, 440, 330, 70);
        getContentPane().add(jAdmi);
        jAdmi.setBounds(0, 0, 750, 560);

        setBounds(0, 0, 770, 596);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login prin;
        prin=new Login();
        this.dispose();
        prin.setVisible(true);
          prin.setLocationRelativeTo(null) ;

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadActionPerformed
      
    }//GEN-LAST:event_txtUnidadActionPerformed

    private void txtUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadMouseClicked

    private void txtUnidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadKeyPressed
        
    }//GEN-LAST:event_txtUnidadKeyPressed

    private void btnMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoActionPerformed
           String U,P,R1,R2,R3,R;
     U=txtUnidad.getText();
     P=txtPregunta.getText(); 
     R1=txtRes1.getText();
     R2=txtRes2.getText();
     R3=txtRes3.getText();
     R=jRes.getText();
        try {
            PreguntasRandom.crearFilePreguntas( new File("preguntas.dat") );
            PreguntasRandom.añadirPregunta( new Preguntas(U,P,R1,R2,R3,R) );
            PreguntasRandom.mostrar();
            PreguntasRandom.cerrar();
            JOptionPane.showMessageDialog(this, "El registro se realizó correctamente.", "Notificación", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error en la escritura de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnMoActionPerformed

    private void txtRes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRes1ActionPerformed

    private void txtRes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRes3ActionPerformed

    private void jResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {  public void run() {
                Search dialog = new Search(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMo;
    private javax.swing.JLabel jAdmi;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jRes;
    private javax.swing.JTextField txtPregunta;
    private javax.swing.JTextField txtRes1;
    private javax.swing.JTextField txtRes2;
    private javax.swing.JTextField txtRes3;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
