/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author sergio
 */
public class Preg extends javax.swing.JFrame {

    contador suma;
    /**
     * Creates new form Preg
     */
    public Preg() {
        suma =new contador();
        
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        Grupo2 = new javax.swing.ButtonGroup();
        Grupo3 = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        Pregunta1 = new javax.swing.JLabel();
        P1R1 = new javax.swing.JRadioButton();
        P1R2 = new javax.swing.JRadioButton();
        P1R3 = new javax.swing.JRadioButton();
        Pregunta2 = new javax.swing.JLabel();
        P2R1 = new javax.swing.JRadioButton();
        P2R2 = new javax.swing.JRadioButton();
        P2R3 = new javax.swing.JRadioButton();
        Pregunta3 = new javax.swing.JLabel();
        P3R1 = new javax.swing.JRadioButton();
        P3R2 = new javax.swing.JRadioButton();
        P3R3 = new javax.swing.JRadioButton();
        BTNAvanzar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuestionario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Transformers Movie", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Cuestionario");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 180, 30));

        Pregunta1.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta1.setText("1- ¿Cuál es la descripción que crees que define mejor el concepto 'clase' en la programación orientada a objetos?");
        getContentPane().add(Pregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 550, 50));

        Grupo1.add(P1R1);
        P1R1.setForeground(new java.awt.Color(255, 255, 255));
        P1R1.setText("a)\tEs un concepto similar al de 'array'");
        getContentPane().add(P1R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 370, -1));

        Grupo1.add(P1R2);
        P1R2.setForeground(new java.awt.Color(255, 255, 255));
        P1R2.setText("b)\tEs un tipo particular de variable");
        getContentPane().add(P1R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 370, -1));

        Grupo1.add(P1R3);
        P1R3.setForeground(new java.awt.Color(255, 255, 255));
        P1R3.setText("c)\tEs un modelo o plantilla a partir de la cual creamos objetos");
        P1R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1R3ActionPerformed(evt);
            }
        });
        getContentPane().add(P1R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, -1));

        Pregunta2.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta2.setText("2- ¿Qué elementos crees que definen a un objeto?");
        getContentPane().add(Pregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 540, 30));

        Grupo2.add(P2R1);
        P2R1.setForeground(new java.awt.Color(255, 255, 255));
        P2R1.setText("a)\tSus cardinalidad y su tipo");
        getContentPane().add(P2R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 400, -1));

        Grupo2.add(P2R2);
        P2R2.setForeground(new java.awt.Color(255, 255, 255));
        P2R2.setText("b)\tSus atributos y sus métodos");
        P2R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2R2ActionPerformed(evt);
            }
        });
        getContentPane().add(P2R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 400, -1));

        Grupo2.add(P2R3);
        P2R3.setForeground(new java.awt.Color(255, 255, 255));
        P2R3.setText("c)\tLa forma en que establece comunicación e intercambia mensajes");
        getContentPane().add(P2R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 400, -1));

        Pregunta3.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta3.setText("3- ¿Qué código de los siguientes tiene que ver con la herencia?");
        getContentPane().add(Pregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 530, 30));

        Grupo3.add(P3R1);
        P3R1.setForeground(new java.awt.Color(255, 255, 255));
        P3R1.setText("a)\tpublic class Componente extends Producto");
        P3R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3R1ActionPerformed(evt);
            }
        });
        getContentPane().add(P3R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 360, -1));

        Grupo3.add(P3R2);
        P3R2.setForeground(new java.awt.Color(255, 255, 255));
        P3R2.setText("b)\tpublic class Componente inherit Producto");
        getContentPane().add(P3R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 360, -1));

        Grupo3.add(P3R3);
        P3R3.setForeground(new java.awt.Color(255, 255, 255));
        P3R3.setText("c)\tpublic class Componente implements Producto");
        getContentPane().add(P3R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 360, -1));

        BTNAvanzar.setText("Siguiente");
        BTNAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAvanzarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 100, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/Descargar Pack Wallpaper Gratis Abstractos (330).jpg"))); // NOI18N
        Fondo.setText("3- ¿Qué código de los siguientes tiene que ver con la herencia?");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 855, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAvanzarActionPerformed
        // TODO add your handling code here:
        int as=0;
        as=suma.getA();
        suma.setA(as);
        Preg1 sg =new Preg1();
        
        sg.setVisible(true);
         dispose();
        
    }//GEN-LAST:event_BTNAvanzarActionPerformed

    private void P1R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1R3ActionPerformed
        // TODO add your handling code here:
        suma.suma();
    }//GEN-LAST:event_P1R3ActionPerformed

    private void P2R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2R2ActionPerformed
        // TODO add your handling code here:
       suma.suma();
    }//GEN-LAST:event_P2R2ActionPerformed

    private void P3R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3R1ActionPerformed
        // TODO add your handling code here:
       suma.suma();
    }//GEN-LAST:event_P3R1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAvanzar;
    private javax.swing.JLabel Fondo;
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.ButtonGroup Grupo2;
    private javax.swing.ButtonGroup Grupo3;
    private javax.swing.JRadioButton P1R1;
    private javax.swing.JRadioButton P1R2;
    private javax.swing.JRadioButton P1R3;
    private javax.swing.JRadioButton P2R1;
    private javax.swing.JRadioButton P2R2;
    private javax.swing.JRadioButton P2R3;
    private javax.swing.JRadioButton P3R1;
    private javax.swing.JRadioButton P3R2;
    private javax.swing.JRadioButton P3R3;
    private javax.swing.JLabel Pregunta1;
    private javax.swing.JLabel Pregunta2;
    private javax.swing.JLabel Pregunta3;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
