/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author sergio
 */
public class Preg1 extends javax.swing.JFrame {

contador sum;
    

    /**
     * Creates new form Preg1
     */
    public Preg1() {
        sum=new contador();
        
        
        
        
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo4 = new javax.swing.ButtonGroup();
        Grupo5 = new javax.swing.ButtonGroup();
        Grupo6 = new javax.swing.ButtonGroup();
        Pregunta4 = new javax.swing.JLabel();
        P4R1 = new javax.swing.JRadioButton();
        P4R2 = new javax.swing.JRadioButton();
        P4R3 = new javax.swing.JRadioButton();
        Pregunta5 = new javax.swing.JLabel();
        P5R1 = new javax.swing.JRadioButton();
        P5R2 = new javax.swing.JRadioButton();
        P5R3 = new javax.swing.JRadioButton();
        Pregunta6 = new javax.swing.JLabel();
        P6R1 = new javax.swing.JRadioButton();
        P6R2 = new javax.swing.JRadioButton();
        P6R3 = new javax.swing.JRadioButton();
        BTNTerminar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuestionario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pregunta4.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta4.setText("4- ¿Qué significa instanciar una clase?");
        getContentPane().add(Pregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 360, 30));

        Grupo4.add(P4R1);
        P4R1.setForeground(new java.awt.Color(255, 255, 255));
        P4R1.setText("a)\tDuplicar una clase");
        getContentPane().add(P4R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 230, -1));

        Grupo4.add(P4R2);
        P4R2.setForeground(new java.awt.Color(255, 255, 255));
        P4R2.setText("b)\tEliminar una clase");
        P4R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4R2ActionPerformed(evt);
            }
        });
        getContentPane().add(P4R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, -1));

        Grupo4.add(P4R3);
        P4R3.setForeground(new java.awt.Color(255, 255, 255));
        P4R3.setText("c)\tCrear un objeto a partir de la clase");
        P4R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4R3ActionPerformed(evt);
            }
        });
        getContentPane().add(P4R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 230, -1));

        Pregunta5.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta5.setText("5- En Java, ¿a qué nos estamos refiriendo si hablamos de 'Swing'?");
        getContentPane().add(Pregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 470, 30));

        Grupo5.add(P5R1);
        P5R1.setForeground(new java.awt.Color(255, 255, 255));
        P5R1.setText("a)\tUna función utilizada para intercambiar valores");
        getContentPane().add(P5R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, -1));

        Grupo5.add(P5R2);
        P5R2.setForeground(new java.awt.Color(255, 255, 255));
        P5R2.setText("b)\tEs el sobrenombre de la versión 1.3 del JDK");
        P5R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P5R2ActionPerformed(evt);
            }
        });
        getContentPane().add(P5R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 270, -1));

        Grupo5.add(P5R3);
        P5R3.setForeground(new java.awt.Color(255, 255, 255));
        P5R3.setText("c)\tUna librería para construir interfaces gráficas");
        P5R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P5R3ActionPerformed(evt);
            }
        });
        getContentPane().add(P5R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 270, -1));

        Pregunta6.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta6.setText("6.-¿Qué es Eclipse?");
        getContentPane().add(Pregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 550, 30));

        Grupo6.add(P6R1);
        P6R1.setForeground(new java.awt.Color(255, 255, 255));
        P6R1.setText("a)\tUna libreria de Java");
        getContentPane().add(P6R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 290, -1));

        Grupo6.add(P6R2);
        P6R2.setForeground(new java.awt.Color(255, 255, 255));
        P6R2.setText("b)\tUna versión de Java especial para servidores");
        getContentPane().add(P6R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 290, -1));

        Grupo6.add(P6R3);
        P6R3.setForeground(new java.awt.Color(255, 255, 255));
        P6R3.setText("c)\tUn IDE para desarrollar aplicaciones");
        P6R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P6R3ActionPerformed(evt);
            }
        });
        getContentPane().add(P6R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 290, -1));

        BTNTerminar.setText("Terminar");
        BTNTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTerminarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 420, 130, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/Descargar Pack Wallpaper Gratis Abstractos (330).jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void P4R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P4R2ActionPerformed

    private void P5R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P5R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P5R2ActionPerformed

    private void P4R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4R3ActionPerformed
        // TODO add your handling code here:
       sum.suma();
    }//GEN-LAST:event_P4R3ActionPerformed

    private void P5R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P5R3ActionPerformed
        // TODO add your handling code here:
        sum.suma();
    }//GEN-LAST:event_P5R3ActionPerformed

    private void P6R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P6R3ActionPerformed
        // TODO add your handling code here:
        sum.suma();
    }//GEN-LAST:event_P6R3ActionPerformed

    private void BTNTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTerminarActionPerformed
        // TODO add your handling code here:
        int aj=0;
        aj=sum.getA();
        sum.setP1(aj);
        int h=aj+sum.getP1();
        String total;
        total="El Total de Puntos es:"+h;
        JOptionPane.showMessageDialog(this,total);
    }//GEN-LAST:event_BTNTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preg1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNTerminar;
    private javax.swing.JLabel Fondo;
    private javax.swing.ButtonGroup Grupo4;
    private javax.swing.ButtonGroup Grupo5;
    private javax.swing.ButtonGroup Grupo6;
    private javax.swing.JRadioButton P4R1;
    private javax.swing.JRadioButton P4R2;
    private javax.swing.JRadioButton P4R3;
    private javax.swing.JRadioButton P5R1;
    private javax.swing.JRadioButton P5R2;
    private javax.swing.JRadioButton P5R3;
    private javax.swing.JRadioButton P6R1;
    private javax.swing.JRadioButton P6R2;
    private javax.swing.JRadioButton P6R3;
    private javax.swing.JLabel Pregunta4;
    private javax.swing.JLabel Pregunta5;
    private javax.swing.JLabel Pregunta6;
    // End of variables declaration//GEN-END:variables
}
